#!/bin/bash
# This script sets up the directory structure. It is assumed that the current working directory is the directory that contains this script
mkdir -p -- ../data
mkdir -p -- ../raw
mkdir -p -- ../processed
mkdir -p -- ../annotation
mkdir -p -- ../data/GEO
mkdir -p -- ../data/TCGA
mkdir -p -- ../data/ENCODE
mkdir -p -- ../raw/GEO
mkdir -p -- ../raw/TCGA
mkdir -p -- ../raw/ENCODE
mkdir -p -- ../processed/GEO
mkdir -p -- ../processed/TCGA
mkdir -p -- ../processed/ENCODE
mkdir -p -- ../processed/GEO/sequencing
mkdir -p -- ../processed/GEO/microarray
