# This script compiles the BTO and DOID ontology of partial GEO datasets, the output file here is annotation/GEO_metadata_test2.txt
GSE102031_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal',16), tissue_name=rep('embryonic stem cell line',16))
GSE111541_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('breast cancer',5),rep('breast cancer-altered',15)), tissue_name=rep('MDA-MB-436 cell',20))
GSE119260_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('adjacent normal',4),rep('prostate cancer',4),rep('adjacent normal',8)), tissue_name=c(rep('prostate gland',8), rep('blood plasma',4),rep('urine',4)))
GSE119778_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('Williams syndrome',34),rep('normal',34)), tissue_name=rep('peripheral blood',68))
GSE121192_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('normal',4),rep('rheumatoid arthritis',10),rep('normal',6),rep('rheumatoid arthritis',10),rep('normal',6),rep('rheumatoid arthritis',10)), tissue_name=c(rep('naive T-lymphocyte',14),rep('memory T-lymphocyte',16),rep('monocyte',16)))
GSE128126_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal',15), tissue_name=rep('embryonic stem cell line',15))
GSE128127_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c('normal','normal-altered', 'normal',rep('normal-altered',5)), tissue_name=rep('embryonic stem cell line',8))
GSE128128_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('normal-altered',2), rep('normal-altered',6)), tissue_name=rep('embryonic stem cell line',8))
GSE130844_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('normal-treated',16)), tissue_name=rep('Hepa-RG cell',16))
GSE131350_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('adrenocortical carcinoma',48),rep('normal',12)), tissue_name=rep('adrenal gland',60))
GSE131677_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('T-cell lymphoblastic lymphoma',49), tissue_name=rep('T-cell lymphoma cell',49))
GSE132181_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal',392), tissue_name=rep(c('umbilical cord blood','peripheral blood mononuclear cell'),196))
GSE132399_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('normal',26),rep('hepatoblastoma',28)), tissue_name=rep('liver',54))
GSE132616_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c('breast cancer','breast cancer-altered'), tissue_name=rep('MCF-7 cell',2))
GSE133801_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('pineoblastoma',43), tissue_name=rep('pineal gland',43))
GSE133985_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep(c('adjacent normal','breast cancer','adjacent normal'),4),c('adjacent normal','adjacent normal'),rep(c('adjacent normal','breast cancer','adjacent normal'),3),c('adjacent normal','breast cancer')), tissue_name=rep('breast epithelial cell',25))
GSE134089_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('neuroendocrine tumor',96), tissue_name=rep('neuroendocrine tumor cell',96))
GSE139404_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c('colorectal adenoma', rep(c('normal','colorectal adenoma','colorectal adenoma'),3),rep(c('normal','colorectal adenoma'),5),rep(c('normal','colorectal adenoma','colorectal adenoma'),4),rep(c('normal','colorectal adenoma'),2),rep(c('colorectal adenoma','colorectal adenoma','normal'),2),'colorectal adenoma','normal','colorectal adenoma','colorectal adenoma','normal','colorectal adenoma','normal','colorectal adenoma','colorectal adenoma','normal',rep('colorectal adenoma',8)), tissue_name=rep('colorectum',60))
GSE140038_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('breast cancer',144),tissue_name=rep('blood',144))
GSE140204_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('sarcomatoid penile squamous cell carcinoma',25), tissue_name=rep('squamous cell carcinoma cell',25))
GSE140800_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('human immunodeficiency virus infectious disease',70), tissue_name=rep('peripheral blood mononuclear cell',70))
# GSE142801_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep(c('normal','undefined'),8))
# GSE143209_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('undefined',64))
GSE145156_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('lung small cell carcinoma',70), tissue_name=rep('small cell lung cancer cell line',70))
#GSE145156_disease<-data.table(sample_id=sample_matrix$Samples, term_name=c('normal','Zika virus congenital syndrome','Zika virus congenital syndrome','normal','Zika virus congenital syndrome'))
GSE146003_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('thyroid gland anaplastic carcinoma',10),rep('normal',4)), tissue_name=c(rep('thyroid gland',14)))
GSE146179_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal-treated',6), tissue_name=rep('RCC 786-O cell',6))
#GSE146426_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('posterior fossa ependymoma',10), tissue_name=rep())
GSE146502_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal-treated',15), tissue_name=rep('bone marrow',15))
GSE147153_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal',9), tissue_name=rep('NCI-H1299 cell',9))
GSE147537_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep(c('breast cancer'),2),c('colorectal cancer','colorectal cancer'),rep(c('breast cancer'),6),c('colorectal cancer','colorectal cancer','breast cancer'),rep('colorectal cancer',6),c('ovarian cancer','colorectal cancer'),rep('ovarian cancer',3),'breast cancer',rep('colorectal cancer',3)), tissue_name=c(rep(c('breast cancer cell'),2),c('colorectal cancer cell','colorectal cancer cell'),rep(c('breast cancer cell'),6),c('colorectal cancer cell','colorectal cancer cell','breast cancer cell'),rep('colorectal cancer cell',6),c('ovary cancer cell','colorectal cancer cell'),rep('ovary cancer cell',3),'breast cancer',rep('colorectal cancer cell',3)))
GSE147740_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal',1129), tissue_name=rep('blood',1129))
GSE149250_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('pancreatic ductal adenocarcinoma',6),rep('normal',9)),tissue_name=rep('pancreas',15))
GSE149282_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep(c('normal','colon cancer'),8),rep(c('colon cancer','normal'),4)), tissue_name=rep('colon',24))
GSE149960_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('Hutchinson-Gilford progeria syndrome',5),rep('normal',6),rep('Hutchinson-Gilford progeria syndrome',4)), tissue_name=rep('skin fibroblast',15))
GSE150901_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal',48), tissue_name=rep('buccal mucosa',48))
GSE151017_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=c(rep('normal',7),'multiple sclerosis','normal',rep('multiple sclerosis',4),rep('normal',7),rep(c('multiple sclerosis','multiple sclerosis','normal','normal'),2),rep('multiple sclerosis',2),'normal',rep('multiple sclerosis',6),rep('normal',9),'multiple sclerosis','normal',rep('multiple sclerosis',4),rep('normal',7), rep(c('multiple sclerosis','multiple sclerosis','normal','normal'),2),'multiple sclerosis','multiple sclerosis','normal',rep('multiple sclerosis',6),'normal','normal'), tissue_name=rep('bronchoalveolar lavage fluid',78))
GSE151042_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal',492), tissue_name=rep('umbilical cord blood',492))
GSE151067_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('intracranial meningioma',88), tissue_name=rep('meninx',88))
GSE151278_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('psoriasis',70), tissue_name=rep('peripheral blood',70))
GSE151355_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('Parkinsons disease',40), tissue_name=rep(c('peripheral blood','brain'),20))
GSE151407_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal',78), tissue_name=rep('vastus lateralis',78))
GSE151485_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal',100), tissue_name=rep('saliva',100))
GSE151600_annot<-data.table(sample_id=sample_matrix$Samples, disease_name=rep('normal',16), tissue_name=rep('skin',16))
GSE151601_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('progeria',6))
GSE151602_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('normal',6))
GSE151603_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('progeria',12))
GSE151604_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('normal',10))
GSE151861_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('colorectal cancer',2))
GSE151862_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('colorectal cancer',5))
GSE152245_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('normal',4))
GSE152380_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('normal',90))
GSE152541_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('colon cancer',16))
GSE152653_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('neuroepithelial tumor',30))
GSE153246_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('normal',6))
GSE153564_disease<-data.table(sample_id=sample_matrix$Samples, term_name=c(rep('normal',3),rep('obesity',3),rep('normal',3),'obesity','obesity','normal','normal',rep('obesity',3)))
GSE153668_disease<-data.table(sample_id=sample_matrix$Samples, term_name=c(rep('normal',5),rep('undefined',5)))
GSE155311_disease<-data.table(sample_id=sample_matrix$Samples, term_name=c(rep(c('serous tubal intraepithelial carcinoma','normal'),8),rep('High grade serous carcinoma tumor',2),rep(c('normal','serous tubal intraepithelial carcinoma'),3),'serous tubal intraepithelial carcinoma','normal',rep('undefined',7)))
GSE155426_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('normal',89))
GSE155952_disease<-data.table(sample_id=sample_matrix$Samples, term_name=c(rep('neonatal sepsis',3),'normal',rep('neonatal sepsis',2),'control',rep('neonatal sepsis',4),rep(c('normal','neonatal sepsis','neonatal sepsis'),2),rep(c('neonatal sepsis','normal','neonatal sepsis'),2)))
GSE156358_disease<-data.table(sample_id=sample_matrix$Samples, term_name=rep('paraganglioma',12))
GSE156792_disease<-data.table(sample_id=sample_matrix$Samples, term_name=c(rep('chronic fatigue syndrome',7),rep('normal',6),rep('chronic fatigue syndrome',6),rep('normal',6),rep('chronic fatigue syndrome',18),rep(c(rep('normal',6),rep('chronic fatigue syndrome',6)),4),rep('normal',4),'chronic fatigue syndrome','normal',rep('chronic fatigue syndrome',5),rep('normal',7)))


all_series_value_name<-sub('_beta_values.txt', '', all_betavalue_name)
all_series_value_name<-sub('data/GEO/', '', all_series_value_name)
disease_matrix<-list()
count=1
for (i in all_series_value_name){
  disease_name<-paste0(i,'_annot')
  if (exists(as.character(disease_name))){
    x=eval(as.name(paste0(i,'_annot')))
    disease_matrix[[count]]=x
    count=count+1
  }
}
all_disease_matrix<-rbindlist(disease_matrix)
write.table(all_disease_matrix,file = 'annotation/GEO_metadata_test2.txt', quote = F, sep = '\t', row.names = F)
